2024-05-07 02:38:03,191 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 02:43:43,638 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 02:43:43,638 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 02:43:53,905 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 03:18:44,136 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 03:18:44,137 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 03:18:59,181 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 03:19:08,756 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 03:19:08,757 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 15:20:25,847 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 18:09:58,807 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 18:09:58,807 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 23:22:22,742 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:22:22,746 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000186A27067A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-07 23:22:22,746 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000186A27068C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-07 23:22:22,747 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000186A2706A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-07 23:24:53,911 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:25:10,895 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 23:25:10,895 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 23:30:01,907 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:30:16,159 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 23:30:16,159 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 23:53:32,226 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:53:43,006 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 23:53:43,006 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 23:55:25,526 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:58:55,523 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 23:58:55,523 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-07 23:59:12,656 - apscheduler.scheduler - INFO - Scheduler started
2024-05-07 23:59:18,916 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-07 23:59:19,000 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-07 23:59:49,849 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-07 23:59:49,849 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:00:00,593 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:00:06,878 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:00:06,961 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:00:22,073 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:00:22,073 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:03:36,739 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:03:36,742 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023783A5CFA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-08 00:03:36,742 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023783A5D0C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-08 00:03:36,742 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023783A5D210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /bot7098871610:AAE-ucrsjqPLk0Y6ed-VYUfSK9YaDpEw4iU/getMe
2024-05-08 00:03:53,662 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:04:02,683 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:04:02,766 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:05:05,070 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:05:05,070 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:05:15,010 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:05:20,881 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:05:20,970 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:06:22,814 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:06:22,901 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:06:46,242 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:06:46,242 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:07:20,160 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:07:24,736 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:07:24,821 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:08:29,908 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:08:29,908 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:08:48,244 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:09:21,037 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:09:21,123 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:09:29,854 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:09:29,854 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:09:33,918 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:09:39,446 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:09:39,532 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:12:58,544 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:12:58,544 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:13:06,237 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:13:13,275 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:13:13,366 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:14:22,948 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:14:22,948 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:32:15,450 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:40:57,070 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:40:57,070 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 00:41:00,825 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 00:41:12,655 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 00:41:12,745 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 00:45:24,551 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 00:45:24,551 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:03:58,990 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:04:23,504 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:04:23,593 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:04:24,605 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:\Users\User\Desktop\PT_START\tg_bot\pt_start_maxim_bot.py", line 57, in get_app_list_choice
    return get_app_list_all(update, context)
  File "c:\Users\User\Desktop\PT_START\tg_bot\pt_start_maxim_bot.py", line 38, in get_app_list_all
    update.message.reply_text(linux('dpkg -l'))
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\message.py", line 764, in reply_text
    return self.bot.send_message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 513, in send_message
    return self._message(  # type: ignore[return-value]
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\extbot.py", line 199, in _message
    result = super()._message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Text is too long
2024-05-08 01:07:15,601 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:07:15,601 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:07:27,532 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:07:47,421 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:07:47,504 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:08:08,643 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:\Users\User\Desktop\PT_START\tg_bot\pt_start_maxim_bot.py", line 65, in get_app_list_choice
    return get_app_list_all(update, context)
  File "c:\Users\User\Desktop\PT_START\tg_bot\pt_start_maxim_bot.py", line 46, in get_app_list_all
    update.message.reply_text(part)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\message.py", line 764, in reply_text
    return self.bot.send_message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 513, in send_message
    return self._message(  # type: ignore[return-value]
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\extbot.py", line 199, in _message
    result = super()._message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 280.0 seconds
2024-05-08 01:14:42,593 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:14:42,593 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:14:55,452 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:15:20,884 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:15:20,968 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:15:48,793 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:15:48,877 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:16:50,724 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:16:50,808 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:16:56,831 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:16:56,919 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:02,636 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:02,720 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:07,689 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:07,772 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:16,041 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:16,124 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:24,709 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:24,793 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:29,537 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:29,620 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:35,197 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:35,280 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:40,317 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:40,402 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:46,166 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:17:46,254 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:17:46,512 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:\Users\User\Desktop\PT_START\tg_bot\pt_start_maxim_bot.py", line 124, in get_ps
    update.message.reply_text(linux('ps -A'))
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\message.py", line 764, in reply_text
    return self.bot.send_message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 513, in send_message
    return self._message(  # type: ignore[return-value]
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\ext\extbot.py", line 199, in _message
    result = super()._message(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "C:\Users\User\Desktop\PT_START\tg_bot\.venv\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message is too long
2024-05-08 01:18:34,692 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:18:34,692 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:18:38,877 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:18:46,521 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:18:46,614 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:18:54,614 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:18:54,703 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:19:07,539 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:19:07,624 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:19:17,370 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_9.6p1)
2024-05-08 01:19:17,452 - paramiko.transport - INFO - Authentication (password) successful!
2024-05-08 01:27:04,044 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:27:04,044 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:29:09,712 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:33:02,172 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:33:02,172 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:33:12,306 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:36:52,628 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:36:52,628 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:36:57,085 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:38:01,315 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:38:01,315 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:38:25,268 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:39:46,183 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:39:46,183 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:39:56,242 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:41:26,237 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:41:26,237 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:41:30,169 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:43:32,060 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:43:32,060 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:43:58,505 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:44:43,907 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:44:43,907 - apscheduler.scheduler - INFO - Scheduler has been shut down
2024-05-08 01:44:53,779 - apscheduler.scheduler - INFO - Scheduler started
2024-05-08 01:45:49,036 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2024-05-08 01:45:49,036 - apscheduler.scheduler - INFO - Scheduler has been shut down
